apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-chaos
  namespace: sock-shop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-cluster-role
  namespace: sock-shop
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-cluster-role-binding
  namespace: sock-shop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-cluster-role
subjects:
- kind: ServiceAccount
  name: argo-chaos
  namespace: sock-shop
