version: '3'

services:
  diag:
    build: .
    volumes:
      - ./:/usr/src/app
    entrypoint: ["/usr/src/app/diag.py"]
  combination:
    build: .
    volumes:
      - ./:/usr/src/app
    entrypoint: ["/usr/src/app/combination.py"]
