namespace: monitoring
resources:
- ./prometheus-sa.yaml
- ./prometheus-cr.yaml
- ./prometheus-crb.yaml
- ./prometheus-exporter-ds.yaml
- ./prometheus-exporter-disk-usage-ds.yaml
- ./prometheus-exporter-kube-state-sa.yaml
- ./prometheus-exporter-kube-state-dep.yaml
- ./prometheus-exporter-kube-state-svc.yaml
- ./prometheus-dep.yaml
- ./prometheus-configmap.yaml
- ./prometheus-svc.yaml
