name: release-tools-tsdr
on:
  push:
    paths:
      - 'tools/tsdr/**'

env:
  DOCKER_BASE_NAME: ghcr.io/${{ github.repository_owner }}/tsdr-tools

jobs:
  docker:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to GitHub Packages
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: tools/tsdr
          push: true
          tags: ${{ env.DOCKER_BASE_NAME }}:latest
